#!/usr/bin/env bash
#Install your load balancer
sudo apt-get update
sudo apt install -y haproxy
sudo sed -i '$ aENABLED=1' /etc/default/haproxy
sudo service haproxy start
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
echo "
frontend http_front
   bind *:80
   mode http
   default_backend http_back

backend http_back
   balance roundrobin
   server 3962-web-01 34.138.111.16:80 check
   server 3962-web-02 54.204.220.203:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart