#!/usr/bin/env bash
#Process and PID file
echo $$ >> /var/run/myscript.pid
trap 'echo I hate the kill command; exit' 15
trap 'echo "Y U no love me?!"' 2
while true; do
	echo 'To infinity and beyond'
done
trap 'rm -rf /var/run/myscript.pid' 3
