#!/usr/bin/env bash
FILE=school
if test -e "$FILE"; then
	echo 'school file exists'
	if test -f "$FILE"; then
		echo 'school is a regular file'
	fi
	if test -s "$FILE"; then
		echo 'school file is not empty'
	else
		echo 'school file is empty'
	fi
else
	echo 'school file does not exists'
fi
