#!/usr/bin/env bash
#Change your home IP
cp /etc/hosts hosts.new
sed -i s/127.0.0.1/127.0.0.2/ hosts.new
if grep "facebook.com" hosts.new
then
	:
else
	echo -e "8.8.8.8\tfacebook.com">>hosts.new
fi
cp -f hosts.new /etc/hosts
