#!/usr/bin/env bash
# Run Nginx as Nginx
pkill apache2
chmod 777 /etc/nginx/nginx.conf
sed -i "/80 default_server/8080 default_server" /etc/nginx/sites-available/default
sed -i "/#user www-data;/user nginx;" /etc/nginx/nginx.conf
su nginx -c "service nginx restart"
