#!/usr/bin/env bash
# 7 lines or less
pkill -9 apache2
chmod 777 /etc/nginx/nginx.conf
sudo sed -i "s/80 default_server/8080 default_server" /etc/nginx/sites-available/default
sudo sed -i "s/#user www-data;/user nginx;" /etc/nginx/nginx.conf
su nginx -c "service nginx restart"
